name: Build and Push to ECR

on:
  push:
    branches:
      - main # 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/login-action@v1
      with:
        registry: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 339388403827.dkr.ecr.ap-south-1.amazonaws.com
        username: AWS
        password: 339388403827.dkr.ecr.ap-south-1.amazonaws.com

    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        # ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REGISTRY: 339388403827.dkr.ecr.ap-south-1.amazonaws.com
        ECR_REPOSITORY: github_samplenode
        IMAGE_TAG: sample_image
      run: |
        docker login 339388403827.dkr.ecr.ap-south-1.amazonaws.com
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
